// These models describe the structure of the api-meta.json file supplied by this module (internally and
// automatically generated by generatemeta script as part of build process).
// 
// Nb. For testing and advanced use only. Most API users will not need this.

/**
 * Base interface for containing common meta-data for
 * reflective access to API classes, properties, 
 * methods, constructors etc.
 */
export interface SymbolEntry {
    comment?: string;
    name: string;
    documentation: string;
    tsType: string;
    jsType?: string;
}

/**
 * Meta-data for reflective access to API classes.
 */
export interface ClassEntry extends SymbolEntry {
    methods:  MethodEntry[];
    properties:  PropertyEntry[];
}

/**
 * Meta-data for reflective access to API class properties.
 */
export interface PropertyEntry extends SymbolEntry {
    readonly: boolean;
}

/**
 * Meta-data for reflective access to API class methods.
 */
export interface MethodEntry extends SymbolEntry {
    parameters: ParameterEntry[];
}

/**
 * Meta-data for reflective access to API method parameters.
 */
export interface ParameterEntry extends SymbolEntry {
    optional: boolean;
}

/**
 * The meta API that classes with meta information shold support.
 */
export interface MetaApi {
    getMeta() : ClassEntry; 
}
